name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AZURE_WEB_APP_NAME: EasyTeams
  AZURE_WEB_APP_PACKAGE_PATH: "./publish"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ./EasyTeams.sln

      - name: Build
        run: dotnet build ./EasyTeams.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./EasyTeams.sln --configuration Release --no-build --output '${{ env.AZURE_WEB_APP_PACKAGE_PATH }}'

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEB_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEB_APP_PACKAGE_PATH }}
